### ISSUE TITLE
ClasscastException while Play + Spring auto reload

### ISSUE THREAD

**Issue by parani-itl** [modelmapper/modelmapper#161]
ClasscastException is thrown by model mapper, when application auto reload happens.

Detailed description is available in 
http://stackoverflow.com/questions/32127438/classcastexception-in-modelmapper-enhancerbymodelmapper-cannot-be-cast

Jean has provided a possible solution for this. 
Can this be fixed?

**Comment by rafik777** [comment]
I have the same in `spring boot`. :(

**Comment by jhalterman** [comment]
I'm not sure about Jean's solution, but this is something I don't have time to look into myself. I'd be happy to look over a pull request though.

**Comment by Maze-fr** [comment]
I have the same problem with Tomcat 8.5. My use case :
I use Spring Boot for dev, but I deploy on Tomcat.
When I try to undeploy my app from Tomcat, it is messy (I have to stop the app, and to try twice to unload it) but it finally works : there is a known bug on Tomcat about not unloading libraries properly.
Then, when I deploy my app's WAR again, I have the error message, probably because Tomcat didn't manage to unload my libraries properly previously.
When I restart Tomcat, everything is fine.

When I tried to debug it, I found the same thing as the answer in StackOverflow.

I suspect that the problem is `PROPERTY_MAP_CONFIGURE` being static in `ExplicitMappingBuilder` class.

**Comment by chhsiao90** [comment]
we had discussed about the spring boot devtools stuff in #254, and we have documentation for how to integrate with spring-boot-devtools: http://modelmapper.org/user-manual/spring-boot-devtools-integration/.

Tomcat restart issue seems to be different issue, pls create another if you still have this problem ,thanks.

**Comment by Maze-fr** [comment]
I think it's because I shared ModelMapper's JAR between all my apps (in a Tomcat shared folder) and so Tomcat didn't unload things properly.
Now we take ModelMapper's JAR in each WAR, and it looks like we don't have the problem any more (well... nobody told me he has the problem, since then).
