### ISSUE TITLE
Conversion from OffsetDateTime to Timestamp

### ISSUE THREAD

**Issue by mresetar** [modelmapper/modelmapper#200]
So have following scenario:
 sourceType is OffsetDateTime and target is field named productVersion which is of java.sql.Timestamp type. When debugging I can see that destinationPath is set to "productVersion.date." and **destionationType** to **int**. Because of this NumberConverter is used to convert those fields NumberFormatException is thrown:

```
2) Converter org.modelmapper.internal.converter.NumberConverter@11c82829 failed to convert java.time.OffsetDateTime to long.
Caused by: org.modelmapper.MappingException: ModelMapper mapping errors:

1) Error mapping 2017-02-02T12:12:37.415+01:00 to java.lang.Long
Caused by: java.lang.NumberFormatException: For input string: "2017-02-02T12:12:37.415+01:00"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.valueOf(Long.java:803)
	at org.modelmapper.internal.converter.NumberConverter.numberFor(NumberConverter.java:166)
	... 39 more
```
In mapper I have following line:
map(source.getProductVersion()).setProductVersion(null);

To fix this I add a custom converter like this:
               `using(OFFSET_DATE_TIME_TO_TIMESTAMP).map(source.getProductVersion()).setProductVersion(null);`

I also have Spring-Boot registered converter for those 2 types and I expect that those will be used. They are in other cases such as BigDecimal -> Long etc. 

So I believe there is some error in recognizing java.sql.Timestamp and Date types. 

Any hints where to look for destinationType resolver?

Miro

**Comment by chhsiao90** [comment]
Thanks for the reporting.
Yeah, I think there are some issues over here
- Better NumberConverter handling
- Consider java8 time support (it might be in an extension module outside modelmapper-core because currently we are in java 1.5)
- Consider configurable [ConverterStore](https://github.com/modelmapper/modelmapper/blob/master/core/src/main/java/org/modelmapper/internal/converter/ConverterStore.java) and improved how it select a converter [ConverterStore.java#L45-L50](https://github.com/modelmapper/modelmapper/blob/master/core/src/main/java/org/modelmapper/internal/converter/ConverterStore.java#L45-L50) (maybe select FULL match first)

For the first point, I think it might be easier to be addressed than the others.
For the other, I still need take some times to think about it.

But it still cannot solve ```java 1.8 date format > number``` problem.
So currently, you might still need PropertyMap.

**Comment by jhalterman** [comment]
The result of `ConverterStore.getConverters()` can be safely modified to add/remove/replace any of the internal converters, FWIW...

**Comment by chhsiao90** [comment]
> but it is an internal API so ideally this isn't the best approach

Yeah, that's what I concerned 😢 
Still need think a better way that user can configure converters by without touching any of our internal API.

So currently, the actions I can take safely and quickly might be
- ConverterStore select FULL match ConditionalConverter first => So that user can register their ConditionalConverter and can be select by ModelMapper.
- Improved NumberConverter

**Comment by chhsiao90** [comment]
@mresetar -
I had improved how ConverterStore select a ConditionConverter.
After this modification, you can do something like this to convert JSR310 time to number

It's a very roughly example
```java
@Test
public class Jsr310Test {
  private ModelMapper modelMapper;

  static class DateTimeWrapper {
    private LocalDateTime date;

    public DateTimeWrapper(LocalDateTime date) {
      this.date = date;
    }

    public LocalDateTime getDate() {
      return date;
    }

    public void setDate(LocalDateTime date) {
      this.date = date;
    }
  }

  static class NumberWrapper {
    private long date;

    public long getDate() {
      return date;
    }

    public void setDate(long date) {
      this.date = date;
    }
  }

  static class Jsr310Converter implements ConditionalConverter<LocalDateTime, Long> {
    @Override
    public MatchResult match(Class<?> sourceType, Class<?> destinationType) {
      if (LocalDateTime.class.isAssignableFrom(sourceType)
          && Long.class.isAssignableFrom(Primitives.wrapperFor(destinationType)))
        return MatchResult.FULL;
      return MatchResult.NONE;
    }

    @Override
    public Long convert(MappingContext<LocalDateTime, Long> context) {
      return context.getSource().atZone(ZoneId.systemDefault()).toInstant().toEpochMilli();
    }
  }

  @BeforeMethod
  public void setUp() {
    modelMapper = new ModelMapper();
    modelMapper.getConfiguration().getConverters().add(new Jsr310Converter());
  }

  public void shouldMapLocalDateTimeToNumber() {
    System.out.println(modelMapper.map(new DateTimeWrapper(LocalDateTime.now()), NumberWrapper.class).date);
  }
}
```

**Comment by carofe82** [comment]
@chhsiao90 @jhalterman 
I'm subscribed to the activity of the project and I'm really glad to see the increase of activity. Thanks @chhsiao90 for helping out so much.

Just a quick question. Have you guys considered moving this project to an earlier version of Java? I would think that most of the developers using this library they use it for a web application.
According to this survey from zeroturnaround, it may be probably OK to move to at least Java 7:
https://zeroturnaround.com/rebellabs/java-tools-and-technologies-landscape-2016-trends/

- Java 8: 62%
- Java 7: 28%
- Java 6 + Java 5: 10%

**Comment by jhalterman** [comment]
@carofe82 I think it would make sense to move to Java 6 or 7. Issue #44 from a while back would be able to benefit from this move. It would also allow us to put proper @Override annotations back into the classes. These are small things, but still nice.

**Comment by chhsiao90** [comment]
@carofe82 - It's my pleasure to contribute ModelMapper and help people here 😄 

+1 for upgrade to Java 6 or Java 7 (There is no big difference for me between the two version)
And I like Override annotations to prevent us doing wrong thing.

I will plan for that, please stay tuned!

**Comment by jhalterman** [comment]
FWIW, ModelMapper was originally written for Java 6 but there were numerous people still using Java 5 so I downgraded it (so to speak). The only concern with upgrading is it means people who are stuck on older versions can not use the library which is why I wasn't in a hurry to upgrade. An upgrade to 7 might be safe at this point though.

**Comment by chhsiao90** [comment]
You can try [modelmapper-module-java8](https://github.com/chhsiao90/modelmapper-module-java8).
