### ISSUE TITLE
support annotations

### ISSUE THREAD

**Issue by birdfriend** [modelmapper/modelmapper#225]
Hi,

Any plans to support annotations to define mapping? thanks.

**Comment by jhalterman** [comment]
@birdfriend The drawback of annotations is that they require string references, which aren't typesafe or refactoring safe:

```
@MapTo("Foo.name")
class FooDto {
  String name;
}

class Foo {
  byte[] name;
}
```

The above hypothetical annotation-based mapping is problematic due to a type mismatch, but you wouldn't know that until runtime. That's part of the premise of ModelMapper, that unlike other libraries, you map real getters and setters and fields to each other. So problems are apparent at compile time.

Also coming in the next release is the ability to map properties with [method references](https://github.com/modelmapper/modelmapper/pull/215). This is pretty awesome IMO :)

**Comment by deep121** [comment]
@Jonanthan Is there any constraint on name of setter and getter for mapping
field

**Comment by jhalterman** [comment]
@deep121 There's no limitation per se, but by default ModelMapper is only configured to recognize JavaBeans named properties, ex: getFoo, setFoo, isFoo, etc. This is via the JavaBeans NamingConvention and NameTokenizer which are [configured](http://modelmapper.org/user-manual/configuration/) by default. These are used in the [matching process](http://modelmapper.org/user-manual/how-it-works/#matching-process) to determine which source and destination properties match each other.

If you want to be able to match other types of properties/fields/methods, you can easily plugin your own NamingConvention and NameTokenizer.

**Comment by chhsiao90** [comment]
I agreed with @jhalterman and we don't have a plan to support annotation based mapping.
My thought is that the annotations will introduce unneeded dependency between source class and destination class.

But if you had any idea that annotations can bring us some benefits, please kindly let us know, thanks.
