### ISSUE TITLE
Types.isInstantiable returns true for java.util.List

### ISSUE THREAD

**Issue by johnluetke** [modelmapper/modelmapper#237]
When a mapping destination is a list of objects, the check in MappingEngine.typeMap to whether or not the destination can be created returns true. Obviously, this is due to `java.util.List` being an interface.

a) Should an additional check be performed in `Types.isInstantiable` to ensure the class is, in fact instantiable?

b) In the specific use case of `java.util.List` (and maybe the Collections framework in general?), does it make sense to override the proposed behavior in **a)** and have `MappingEngine.createDestination` return a concerete class, such as `java.util.ArrayList`?

**Comment by chhsiao90** [comment]
Thanks for the report.
There are two types about Collection mapping.

##### One is Source[Collection] -> Destination[Collection]
And we already had a predefined [CollectionConverter](https://github.com/modelmapper/modelmapper/blob/master/core/src/main/java/org/modelmapper/internal/converter/CollectionConverter.java) for that, so you don't need to care about the initiating of a Collection.

##### Another Source[Non-Collection-Type] -> Destination[Collection]
For this case, I think you always need a converter for this use case, because even the Collection is initiated, but ModelMapper still doesn't know about how to map a non-collection-type to a collection type. So I think it doesn't matter that the destination collection is initiated of not.

But I'm not sure that these two cases cover all use cases, and it's always good to provide more useful and user-friendly api. So I would like to know what's your use case, and let's find out that ModelMapper API can fulfill the use case or not.

**Comment by chhsiao90** [comment]
I think maybe my previous comment misunderstand about your issue.
Is that your use case had an exception occur that ModelMapper try initiate a List?

**Comment by johnluetke** [comment]
Yes, I had an exception with ModelMapper trying to instantiate a list. 

I'm working on getting a reproduceable code sample
