### ISSUE TITLE
Occasionally model mapper, does not map value (Once in few times)

### ISSUE THREAD

**Issue by magdenkov** [modelmapper/modelmapper#243]
Please see example
https://github.com/magdenkov/protobuf-modelmapper-problem

Thank a lot! 
Or if you can give some idea where can be problem, i will try to create pull request

**Comment by chhsiao90** [comment]
Thanks for the report and the reproducible code, I will take a look!

**Comment by chhsiao90** [comment]
@magdenkov - sorry for the lately reply. I had took a look of your code. Here is my finding.

I failed tests with
- Always failed [TestMappingWithNULLValue#convertProtoBufGeneratedWithNullToDto](https://github.com/magdenkov/protobuf-modelmapper-problem/blob/master/src/test/java/TestMappingWithNULLValue.java#L27)
- Occasionally failed [TestMappingWithTrueValue#convertDtoWithTrueToProtoBufGenerated](https://github.com/magdenkov/protobuf-modelmapper-problem/blob/master/src/test/java/TestMappingWithTrueValue.java#L24)

It seems that my test result is different to your test result described in [README.md](https://github.com/magdenkov/protobuf-modelmapper-problem/blob/master/README.md).

#### TestMappingWithNULLValue#convertProtoBufGeneratedWithNullToDto
[source code](https://github.com/magdenkov/protobuf-modelmapper-problem/blob/master/src/test/java/TestMappingWithNULLValue.java#L27)

Though ```testBoolValue.hasSomeBoolValue()``` return false, but I found that ```testBoolValue.getSomeBoolValue()``` always have value and ```testBoolValue.getSomeBoolValue().getValue()``` will get ```false```.

```java
   public void convertProtoBufGeneratedWithNullToDto() {
        ModelMapper modelMapper = ModelMapperFactory.getConfiguredModelMapper();
        ProtoCommon.TestBoolValue testBoolValue = ProtoCommon.TestBoolValue.newBuilder().build();
        assertFalse(testBoolValue.hasSomeBoolValue());
        assertNull(testBoolValue.getSomeBoolValue()); // This will fail because someBoolValue always had value

        BooleanDto dto = modelMapper.map(testBoolValue, BooleanDto.class);

        assertNull(dto.getSomeBoolValue());  // this will fail since default will be always false
    }
```

#### TestMappingWithTrueValue#convertDtoWithTrueToProtoBufGenerated
[source code](https://github.com/magdenkov/protobuf-modelmapper-problem/blob/master/src/test/java/TestMappingWithTrueValue.java#L24)
It occasionally failed because that protocol buffer gen code had two setter with same name.
One is [Builder setSomeBoolValue(BoolValue)](https://github.com/magdenkov/protobuf-modelmapper-problem/blob/master/gen/main/java/com/vach/common/proto/ProtoCommon.java#L445) and the other is [Builder setSomeBoolValue(Builder)](https://github.com/magdenkov/protobuf-modelmapper-problem/blob/master/gen/main/java/com/vach/common/proto/ProtoCommon.java#L461-L462).
Sometimes ModelMapper will choose the first one as the setter (We called mutator in ModelMapper) , and sometimes ModelMapper will choose the second one.
When ModelMapper choose the second one and the mapping will fail.
And when ModelMapper choose one, the result will be cached, so when it success once, it success always, so as failed case.

#### My briefly thought
I think all of the two cases seem not a bug of ModelMapper.
But I know there is a lot of user use protocol buffer, so I will think about that is there any safe way to improved about integration with protocol buffer, and I will think about some workaround for your case(Or maybe you already have one).

**Comment by magdenkov** [comment]
@chhsiao90  Thank you for investiagtion. 
Actually, my results are the same as your , just made a missprint in README.

1) Also we found another mistery case....
Some times does not map values that starts with "w"
[Like in this test that i ve added](https://github.com/magdenkov/protobuf-modelmapper-problem/blob/master/src/test/java/NotMappingValuesStartsWithW.java#L22)

2) regarding null values workaround is just mapping them manually... 
And i am wondering is it possible to do something like 
`if  (source.getParent().hasSomeBoolValue()) {
 return value;
 } else {
 return null;
}`
directly in converter?
May be with some Reflection?) 

3) regarding 2 setters will try to invent workaround. Note: 2 getters are being generated only when using protobuf wrappers(fields that can be null)  In other cases protobuf generates only one setter and model mapper works just fine(except case about values that starts with  "W")

**Comment by magdenkov** [comment]
for 3-d case i've found work around)

**Comment by magdenkov** [comment]
So with third case helped just adding new converter for builder. [Converter](https://github.com/magdenkov/protobuf-modelmapper-problem/blob/master/src/main/java/com/vach/sample/ModelMapperFactory.java#L47)

**Comment by magdenkov** [comment]
BTW @chhsiao90  What do you think, about making ModelMapper a little bit more smart, so it can choose setter not only by name but also by type? in cases when there are 2 or more setters. This will be kind of feature request?

**Comment by idntfy** [comment]
any update on this? faced the same issue

**Comment by chhsiao90** [comment]
Hi, sorry... I don't have any update on this issue...
I know this issue is very important but I still don't have time to look at this issue...
I will take a look at this issue when I have time...

If anyone interested at this one, PR is welcome! Thanks!

**Comment by kobbikobb** [comment]
Tried TestMappingWithNULLValue.convertDtoWithNullToProtoBufGenerated 10.000 times, no error...
Tried NotMappingValuesStartsWithW.mapping test 1000 times, no error...

**Comment by chhsiao90** [comment]
Hi @kobbikobb  - Comment the line here https://github.com/magdenkov/protobuf-modelmapper-problem/blob/master/src/main/java/com/vach/sample/ModelMapperFactory.java#L22 and the test will fail.

**Comment by ivanarkhipov** [comment]
Any update on this issue?

**Comment by chhsiao90** [comment]
Sorry... I will work on this about modelmapper/protocol-buffer stuff.

**Comment by chhsiao90** [comment]
I will create a modelmapper-module-protobuf for better protocol buffer support.

**Comment by magdenkov** [comment]
@chhsiao90 Wow, that would be awesome!! Thx, in advance!

**Comment by chhsiao90** [comment]
What's the common use case for using ModelMapper with protocol buffer?

- Protobuf POJO -> Protolbuf POJO builder
- Protobuf pritmive type -> Java primitive type
- Java primitive type -> Protobuf pritmive type

Any else?

**Comment by chhsiao90** [comment]
I'm trying to implement module for protocol buffer: #357.
