### ISSUE TITLE
Why are examples not a module of parent?

### ISSUE THREAD

**Issue by ehmkah** [modelmapper/modelmapper#245]
I wanted to write a small example for mapping inheritance in the example folder. Why is examples not a module of the parent? 

Now examples uses 0.6.5.2 of modelmapper which does not match to 1.0.0 which is the current version.

**Comment by jhalterman** [comment]
Would be happy to take an inheritance example if you want to contribute.

The reason examples is not a module of the parent is because that would cause the examples to be included as part of the release to maven central (by default). I think there's a way of excluding modules from being part of a release, I just haven't looked into it.

**Comment by ehmkah** [comment]
Ui, that was a fast answer :-) 

Do you really see a problem if the examples are uploaded to maven central? Because than 
a) there would always be a working example for a specific version of modelmapper
b) it's easier to understand if the project is checked out

**Comment by ehmkah** [comment]
Anyway - I prepared a pull-request which you can take if you want. Or decline it.

I am going to write the examples for inheritance anyway.

**Comment by chhsiao90** [comment]
I'm both fine to include or not include the example into a submodule of modelmapper. I'm not sure that is there any disadvantage to have it to be release to maven central. I take a look some java popular OSS project, and it seems that they all include the example into maven release, like [netty](http://central.maven.org/maven2/io/netty/netty-example/) and [okhttp3](http://central.maven.org/maven2/com/squareup/okhttp3/sample/). So I preferred to have it to be included in our release.

**Comment by jhalterman** [comment]
I just remembered where I had done this before:

https://github.com/atomix/atomix/blob/master/examples/pom.xml#L59-L76

That allows the examples to be a module while being skipped for javadocs and the release, so we should be able to include it and do something like that.

**Comment by ehmkah** [comment]
If I added the lines you mentioned to example/pom.xml would he pull-request gets a better chance of beeing accepted?

**Comment by chhsiao90** [comment]
I think currently the PR looks great. But we still need discussion to make the decision that should example be deployed to maven central or not. Both options looks good to me, because I don't know the advantage/disadvantage between these two option.

But you can add the lines into your PR and I will have a review and merge it. If we decide to deploy example to maven central, then we can remove it again.

**Comment by jhalterman** [comment]
AFAIK, there's no point in deploying examples to maven central since they're only useful as source code, not binaries. We can still switch them to being modules and just exclude from releases though as shown in the link above.

**Comment by chhsiao90** [comment]
@ehmkah - Let's do it!

**Comment by ehmkah** [comment]
updated the pull-request with the provided maven-configuration. Thanks for your support.

Unfortunately the fomatting has been destroyed :-( It has now IntelliJ default

**Comment by chhsiao90** [comment]
Had been fixed by #246
@ehmkah - thanks for your contribution!
