### ISSUE TITLE
Property Condition Not Applied to Nested Members

### ISSUE THREAD

**Issue by michaelcowan** [modelmapper/modelmapper#325]
I use ModelMapper to apply modifications to a class from another instance of the same class. Any null values are to be treated as _don't modify value_
e.g. given the object ...
```json
{
  "id" : "my-id",
  "type" : "my-type"
}
```
... and applying the modification ...
```json
{
  "id": null,
  "type": "new-type"
}
```
... I get
```json
{
  "id" : "my-id",
  "type" : "new-type"
}
```

This works well using the following:
```java
ModelMapper modelMapper = new ModelMapper();
modelMapper.getConfiguration().setPropertyCondition(Conditions.isNotNull());

modelMapper.map(modifications, original);
```

However, if my POJO contains a non primitive type, then the `isNotNull()` condition is not applied.

e.g.

```java
Purchasable purchasable = new Purchasable("my-id", "my-label");
purchasable.setChargingModel(new ChargingModel("my-unit", 5));

Purchasable modifications = new Purchasable(null, "new-label");
modifications.setChargingModel(new ChargingModel(null, 2));

buildModelMapper().map(modifications, purchasable);

assertThat(purchasable.getId(), equalTo("my-id"));                          // Passes
assertThat(purchasable.getLabel(), equalTo("new-label"));                   // Passes
assertThat(purchasable.getChargingModel().getCap(), equalTo(2));            // Passes
assertThat(purchasable.getChargingModel().getUnit(), equalTo("my-unit"));   // Fails - value is null
```

I have recreated the issue in the form of a test [here](https://pastebin.com/GiY2UP19)

**Comment by chhsiao90** [comment]
It's a known issue that ModelMapper will assign the reference of the source's property to destination instead of create a new one if they are same types.

I think you can find `purchasable.getChargingModel() == modifications.getChargingModel()` to be `true` that the puchasable's chargingModel is overwrite by modifications' chargingModel.

I will create a configuration, maybe named `alwaysCopy` and I think that will fix this issue.

**Comment by chhsiao90** [comment]
Now you can use `deepCopyEnabled` #343
