### ISSUE TITLE
In 2.2.0 using ModelMapper to map to a class using a converter causes a NPE

### ISSUE THREAD

**Issue by vamadou** [modelmapper/modelmapper#388]
Since release 2.2.0 the following code will crash due to a NPE

    ModelMapper modelMapper = new ModelMapper();
    Converter<From, To> fromToConverter = new Converter<From, To>() {
        public To convert(MappingContext<From, To> context) {
            From from = context.getSource();
            // Will cause a NPE when map method is called with Class param
            To to = context.getDestination();
            return to;
        }
    };
    modelMapper.addConverter(fromToConverter);

    From myFrom = new From();

    // Will crash with version 2.2.0
    To to = modelMapper.map(myFrom, To.class);

Reason seems to be that the destination object is not instantiated and put in the context before calling the converter ... the code doing this is in class MappingEngineImpl.java and seems to have been "moved" in a wrong position in the new version commited for 2.2.0

**Comment by vamadou** [comment]
Sorry bad explanation ... but check the value of the `context.getDestination()`in your Converter ... it will be null

**Comment by chhsiao90** [comment]
If you are using converter to convert a source to destination, then ModelMapper won't create the destination instance for you. I think it's working as design.

Can you share your use case?

**Comment by vamadou** [comment]
Hum hum 🤔 I think I understand what you mean, I’ll double check ... was working correctly before 2.2.0 though

**Comment by vamadou** [comment]
I'll change my code to pass an instance iso a type in my modelMapper.map(...) invocation

Two remarks though, because even though it may be working as designed and I do understand the Converter point-of-view: 
- it was working correctly before 2.2.0 and nothing in doc/code prevented it so maybe add something to the release note/doc
- Finally I find it a bit sad to have to know how the mapping between two objects is actually implemented (your magic ;-) or a blunt converter) to decide which version of the `map()` method I can use

Thanks, you can close the ticket if you think it doesn't make sense

**Comment by chhsiao90** [comment]
> it was working correctly before 2.2.0 and nothing in doc/code prevented it so maybe add something to the release note/doc

Currently, we have [CHANGES.md](https://github.com/modelmapper/modelmapper/blob/master/CHANGES.md) for the release note. But I'm not sure if it's good enough to notice user how the upgrade impact on their program. Please let me know if you have any good idea that we can improve about how to notify users with these broken changes?

> Finally I find it a bit sad to have to know how the mapping between two objects is actually implemented (your magic ;-) or a blunt converter) to decide which version of the map() method I can use

I'm trying hard to make the mappings more reasonable and straight-forward for every users. But different users will have different idea for how should ModelmMapper do.

For example, I found this issue was caused by #384 for the issue #151. 
In the [comment#307340650](https://github.com/modelmapper/modelmapper/issues/151#issuecomment-307340650), it convince me it's a bug to create a destination before convert a source to a destination because this behavior was already described in the javadoc [Converter](http://modelmapper.org/javadoc/org/modelmapper/Converter.html): `Converts instances of source type S to instances of destination type D.`. So I'm trying to reduce users from base on some bad behavior of ModelMapper with my every commits and hope that it won't impact to any users.

Thanks for your feedback, it's very helpful. And sorry for the bad experience you have.

**Comment by vamadou** [comment]
I know the drill, always difficult to please everyone. No problem.
Keep up the good work.
