### ISSUE TITLE
Update the documentation

### ISSUE THREAD

**Issue by devlifealways** [modelmapper/modelmapper#474]
I think the explicit mapping section should be improved, the typeMap is not really clear at first glance. If you can explicitly put an example for others to see that for instance __modelMapper.createMap__ could be used to customize more the mapping between source and target classes.

Thank you in advance,

**Comment by nilskuhn** [comment]
The example for explicit mapping with Java 8+ is just not compiling! 

```
modelMapper.addMappings(mapper -> {
  mapper.map(src -> src.getBillingAddress().getStreet(),
      Destination::setBillingStreet);
  mapper.map(src -> src.getBillingAddress().getCity(),
      Destination::setBillingCity);
});
```
To use explicit mapping with Java 8 and lambdas one need to call `addMappings` on a created TypeMap instead of the modelMapper itself (which `addMappings` method takes a PropertyMap):
```
TypeMap<Order, OrderDTO> typeMap = 
    modelMapper.createTypeMap(Src.class, Destination.class);
```
That should be stated clearly in documentation. 

It's really annoying to start with this experience on a Getting Started!

**Comment by chhsiao90** [comment]
Thanks for reporting the issue, the bug was fixed in https://github.com/modelmapper/modelmapper.github.io/issues/2
