### ISSUE TITLE
Overriding values while mapping to DTO

### ISSUE THREAD

**Issue by Blvckhype** [modelmapper/modelmapper#581]
Hi

I encountered some issues with data mapping with more complicated DTO's. I have two DTO's one of them has list of LanguageDTO as his property (called HubDTO), second one has two individual instances of LangaugeDTO and nested HubDTO. ModelMapper  produces DTO with overridden values in this two instances (to be specific first instance has overridden values from second one). If I comment HubDTO, both instances are mapped correctly.

This is my modelMapper configuration

```
modelMapper
                .getConfiguration()
                .setPropertyCondition(Conditions.isNotNull())
                .setMatchingStrategy(MatchingStrategies.STRICT);
```

This is HubDTO
```
public class HubDTO extends SimpleHubDTO {

    private List<LanguageDTO> languages;
}
```

This is my second DTO
```
public class EditRequestDTO extends RequestBaseDTO {

    private HubDTO hub;

    private LanguageDTO primaryLanguage;

    private LanguageDTO secondaryLanguage;
}
```

LanguageDTO is just a simply DTO with only two properties (id, name)

Is there any solution to resolve this, or this is a bug?

**Comment by lolo101** [comment]
I believe I met the same issue.
I built a small demo of the bug here : https://github.com/lolo101/modelmapper-bug

The bug occurs in a very specific case :

you need to have a collection of some Type,
another property of the same Type that is equal to some element of the collection
another property of the same Type that is different from the previous property

**Comment by chhsiao90** [comment]
Thanks @lolo101 for the reproducible code, it's very helpful.

It's caused by [MappingContextImpl](https://github.com/modelmapper/modelmapper/blob/modelmapper-parent-2.3.9/core/src/main/java/org/modelmapper/internal/MappingContextImpl.java#L313) for supporting circular reference mapping (see [CircularDependencies5](https://github.com/modelmapper/modelmapper/blob/modelmapper-parent-2.3.9/core/src/test/java/org/modelmapper/functional/circular/CircularDependencies5.java)).

I'm trying to make both scenario passed.

**Comment by chhsiao90** [comment]
ModelMapper 2.4.0 released.
