### ISSUE TITLE
Conditional skipping is not working

### ISSUE THREAD

**Issue by micobarac** [modelmapper/modelmapper#588]
I have the following issue.

This is working:

```java
mapper.when(Conditions.isNotNull()).map(AccountUpdateVM::getPackets, Account::setPackets);
```

This is **NOT** working:

```java
mapper.when(Conditions.isNull()).skip(Account::setPackets);
```

I even created the custom condition. I can see that the condition is met at some point, but the property is not skipped.

**Comment by chhsiao90** [comment]
It's expected behavior, using skip directly means that the no source property will be mapped to the destination property, no matter what the condition is.

I guessed it's very confusing to chain a skip with a when, users might think if the destination property will be set if the condition mismatch.
I will consider to disallow to chain a skip after a when, but I'm not sure if there is any use case that need this feature.

**Comment by micobarac** [comment]
Shouldn't skip do the opposite of map, combined with when? It's really confusing.

**Comment by chhsiao90** [comment]
`skip` means that no source properties will map to the destination property. Also, we cannot define which source property should be used for the skipped destination property in a `skip` call.

So, it's not opposite of `map`.

**Comment by chhsiao90** [comment]
Hi @micobarac ,

I just check the legacy api which supports conditional skip with configured source getter. I will update the functional api to support same functionality. (see [Conditional Mapping](http://modelmapper.org/user-manual/property-mapping/#conditional-mapping))

Thanks for reporting this issue.

**Comment by chhsiao90** [comment]
ModelMapper 2.4.0 released.
