### ISSUE TITLE
Bio directional object within list does not map object.

### ISSUE THREAD

**Issue by beachygreg** [modelmapper/modelmapper#59]
I am mapping a given object to a object of the same type. One of the sets within the source has a object that references the original object (if that is clear?). 

Example:
class A {
 Set<B> bs;
}

class B {
 A a;
}

The problem is after mapping a instance of A to A, say a1 to a2. we can get b2 but that sub object in the set has a reference to a1 and not its parent a2.

**Comment by dr3s** [comment]
+1 it would nice if it was configurable to always create new objects when mapping properties such that it is easy to do a deep clone.  Currently, mapping from:

```java
public class A {
   private B b;
}
```

to:

```java
public class C {
   private B b;
}
```

results in a.b == c.b

**Comment by RajuGR** [comment]
I'm also facing the same issue. Is there any alternative solution for this?

**Comment by chhsiao90** [comment]
Yeah..
The problem might be caused by [AssignableConverter](https://github.com/modelmapper/modelmapper/blob/master/core/src/main/java/org/modelmapper/internal/converter/AssignableConverter.java) in [ConverterStore](https://github.com/modelmapper/modelmapper/blob/master/core/src/main/java/org/modelmapper/internal/converter/ConverterStore.java)

Currently, it seems to be hard to disable the converter because
- AssignableConverter have no configuration
- The method ```match``` only have source type and destination type as the arguments
- There is no nice way to config the converter store

The workaround might be to remove  the converter manually.
Not very recommend, but please to have some complete test you want to try it.
```java
  // really ugly workaround
  ConditionalConverter<?, ?> assignableConverter = null;
    for (ConditionalConverter<?, ?> converter : modelMapper.getConfiguration().getConverters()) {
      if (converter instanceof  AssignableConverter) {
        assignableConverter = converter;
        break;
      }
    }
    if (assignableConverter != null) {
      modelMapper.getConfiguration().getConverters().remove(assignableConverter);
    }
```

**Comment by chhsiao90** [comment]
ModelMapper now support `modelMapper.getConfiguration().setDeepCopyEnabled(true)`: #343
